/home/cc/miniconda/lib/python3.12/site-packages/langchain/tools/__init__.py:63: LangChainDeprecationWarning: Importing tools from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.tools import DuckDuckGoSearchRun`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
2024-06-19 14:14:07,050 - 140422725903936 - _common.py-_common:105 - INFO: Backing off send_request(...) for 0.5s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:07,072 - 140422717511232 - _common.py-_common:105 - INFO: Backing off send_request(...) for 0.4s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:07,126 - 140422708069952 - _common.py-_common:105 - INFO: Backing off send_request(...) for 0.4s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:07,147 - 140422699677248 - _common.py-_common:105 - INFO: Backing off send_request(...) for 0.7s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:07,507 - 140422717511232 - _common.py-_common:105 - INFO: Backing off send_request(...) for 0.3s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:07,550 - 140422725903936 - _common.py-_common:105 - INFO: Backing off send_request(...) for 1.9s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:07,576 - 140422708069952 - _common.py-_common:105 - INFO: Backing off send_request(...) for 0.5s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:07,796 - 140422717511232 - _common.py-_common:105 - INFO: Backing off send_request(...) for 1.7s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:07,881 - 140422699677248 - _common.py-_common:105 - INFO: Backing off send_request(...) for 0.2s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:08,127 - 140422708069952 - _common.py-_common:105 - INFO: Backing off send_request(...) for 2.3s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:08,136 - 140422699677248 - _common.py-_common:105 - INFO: Backing off send_request(...) for 0.1s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:08,207 - 140422699677248 - _common.py-_common:120 - ERROR: Giving up send_request(...) after 4 tries (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:09,412 - 140422725903936 - _common.py-_common:105 - INFO: Backing off send_request(...) for 1.6s (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:09,471 - 140422717511232 - _common.py-_common:120 - ERROR: Giving up send_request(...) after 4 tries (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:10,428 - 140422708069952 - _common.py-_common:120 - ERROR: Giving up send_request(...) after 4 tries (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
2024-06-19 14:14:11,023 - 140422725903936 - _common.py-_common:120 - ERROR: Giving up send_request(...) after 4 tries (requests.exceptions.SSLError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1000)'))))
