Traceback (most recent call last):
  File "/mnt/d/project/zzbc/experiment_project/experiment_project/moxin/agent/selfrefine_agent.py", line 6, in <module>
    import dspy
  File "/home/cc/miniconda/envs/agent_py11/lib/python3.11/site-packages/dspy/__init__.py", line 1, in <module>
    import dsp
  File "/home/cc/miniconda/envs/agent_py11/lib/python3.11/site-packages/dsp/__init__.py", line 1, in <module>
    from .modules import *
  File "/home/cc/miniconda/envs/agent_py11/lib/python3.11/site-packages/dsp/modules/__init__.py", line 22, in <module>
    from .pyserini import *
  File "/home/cc/miniconda/envs/agent_py11/lib/python3.11/site-packages/dsp/modules/pyserini.py", line 4, in <module>
    from datasets import Dataset
  File "/home/cc/miniconda/envs/agent_py11/lib/python3.11/site-packages/datasets/__init__.py", line 22, in <module>
    from .arrow_dataset import Dataset
  File "/home/cc/miniconda/envs/agent_py11/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 59, in <module>
    import pyarrow as pa
  File "/home/cc/miniconda/envs/agent_py11/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: /home/cc/miniconda/envs/agent_py11/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/cc/miniconda/envs/agent_py11/lib/python3.11/site-packages/pyarrow/libarrow_acero.so.1600)
